version: "3.7"
services:
  influxdb:
    image: "quay.io/influxdb/influxdb:2.0.0-alpha"
    ports:
      - "9999:9999"
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      backend:
        ipv4_address: 10.10.0.13
  
  redis:
    container_name: influx-monitoring-redis
    image: redis
    restart: always
    hostname: influx-monitoring-redis
    volumes:
      - influx-monitoring-redis:/redis/data
    ports:
      - 6379:6379
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      backend:
        ipv4_address: 10.10.0.14
        
volumes:
  influx-monitoring-redis:
    external: true
        
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
