export enum EnvConfig {
  APP_PORT = 'APP_PORT',
  VISITOR_UNIQUE_BY_IP_MODE = 'VISITOR_UNIQUE_BY_IP_MODE',
  REDIS_URL = 'REDIS_URL',
  INFLUX_URL = 'INFLUX_URL',
  INFLUX_TOKEN = 'INFLUX_TOKEN',
  INFLUX_ORG = 'INFLUX_ORG',
  INFLUX_BUCKET = 'INFLUX_BUCKET',
  INFLUX_USER = 'INFLUX_USER',
  INFLUX_PASS = 'INFLUX_PASS',
}
